export const DEFAULT_NEWS_SOURCES = [
  {
    sourceId: "sec-press-releases",
    name: "SEC Press Releases",
    description:
      "Official SEC press releases, enforcement actions, policy updates, and market-regulatory announcements.",
    sourceUrl: "https://www.sec.gov/news/pressreleases.rss",
    sourceTier: "official-regulatory",
    category: "Regulatory / Legal",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 86,
    maxItemsPerRun: 20,
    cooldownMinutes: 10,
    priority: 1,
  },
  {
    sourceId: "sec-structured-us-gaap",
    name: "SEC Structured Disclosure Feed",
    description:
      "SEC structured disclosure feed for XBRL submissions and filing-related materials.",
    sourceUrl: "https://www.sec.gov/Archives/edgar/usgaap.rss.xml",
    sourceTier: "official-regulatory",
    category: "SEC Filings",
    enabled: true,
    minScoreToRetain: 52,
    minScoreToAlert: 84,
    maxItemsPerRun: 25,
    cooldownMinutes: 10,
    priority: 1,
  },
  {
    sourceId: "nasdaq-trade-halts",
    name: "Nasdaq Trade Halts",
    description:
      "Nasdaq Trader RSS feed for trading halts and urgent exchange-level market events.",
    sourceUrl: "https://www.nasdaqtrader.com/rss.aspx?feed=tradehalts",
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 45,
    minScoreToAlert: 80,
    maxItemsPerRun: 20,
    cooldownMinutes: 5,
    priority: 1,
  },
  {
    sourceId: "nasdaq-current-headlines",
    name: "Nasdaq Trader Current Headlines",
    description:
      "Nasdaq Trader current headline feed for market-structure and exchange alerts.",
    sourceUrl:
      "https://www.nasdaqtrader.com/rss.aspx?categorylist=0&feed=currentheadlines",
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 86,
    maxItemsPerRun: 20,
    cooldownMinutes: 10,
    priority: 2,
  },
  {
    sourceId: "demo-sec",
    name: "Demo SEC Filing Feed",
    description:
      "Demo source used when live RSS feeds are unavailable or while testing the algorithm.",
    sourceUrl: null,
    sourceTier: "official-regulatory",
    category: "SEC Filings",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 88,
    maxItemsPerRun: 25,
    cooldownMinutes: 10,
    priority: 8,
  },
  {
    sourceId: "demo-exchange",
    name: "Demo Exchange Halt Feed",
    description:
      "Demo exchange source used to test trading-halt style urgency logic.",
    sourceUrl: null,
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 50,
    minScoreToAlert: 82,
    maxItemsPerRun: 20,
    cooldownMinutes: 5,
    priority: 8,
  },
  {
    sourceId: "demo-market",
    name: "Demo Market News",
    description:
      "Demo general market headlines used to validate company and sector matching.",
    sourceUrl: null,
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 60,
    minScoreToAlert: 90,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 9,
  },
  {
    sourceId: "demo-macro",
    name: "Demo Macro Feed",
    description:
      "Demo macro source for rates, yields, inflation, and bond-sensitive headlines.",
    sourceUrl: null,
    sourceTier: "macro-source",
    category: "Macro / Rates",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 86,
    maxItemsPerRun: 25,
    cooldownMinutes: 15,
    priority: 9,
  },
  {
    sourceId: "demo-earnings",
    name: "Demo Earnings Feed",
    description:
      "Demo earnings source for financial results, guidance, and margin commentary.",
    sourceUrl: null,
    sourceTier: "market-news",
    category: "Earnings / Guidance",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 86,
    maxItemsPerRun: 25,
    cooldownMinutes: 15,
    priority: 9,
  },
  {
    sourceId: "demo-crypto",
    name: "Demo Crypto Feed",
    description:
      "Demo crypto source for digital asset risk and institutional-flow headlines.",
    sourceUrl: null,
    sourceTier: "crypto-source",
    category: "Crypto / Digital Assets",
    enabled: true,
    minScoreToRetain: 65,
    minScoreToAlert: 92,
    maxItemsPerRun: 20,
    cooldownMinutes: 20,
    priority: 9,
  },
  {
    sourceId: "demo-venture",
    name: "Demo Venture Feed",
    description:
      "Demo venture source for private market and startup-theme categorization.",
    sourceUrl: null,
    sourceTier: "venture-source",
    category: "Private Markets / Venture",
    enabled: true,
    minScoreToRetain: 68,
    minScoreToAlert: 95,
    maxItemsPerRun: 15,
    cooldownMinutes: 30,
    priority: 9,
  },
  {
    sourceId: "demo-noise",
    name: "Demo Noisy Feed",
    description:
      "Low-trust demo source used to make sure promotional garbage is suppressed.",
    sourceUrl: null,
    sourceTier: "unknown",
    category: "Noise Testing",
    enabled: true,
    minScoreToRetain: 80,
    minScoreToAlert: 99,
    maxItemsPerRun: 5,
    cooldownMinutes: 60,
    priority: 10,
  },
];

export const DEFAULT_RETENTION_POLICY = {
  minScoreToStore: 55,
  minScoreToAlert: 88,
  maxRetainedPerRun: 40,
  maxRetainedDecisions: 600,
  maxRetainedRuns: 50,
  maxAlertEvents: 400,
  urgentRetentionDays: 45,
  reviewRetentionDays: 30,
  digestRetentionDays: 14,
  watchRetentionDays: 5,
  readAlertRetentionDays: 30,
};