export const DEFAULT_NEWS_SOURCES = [
  // ---------------------------------------------------------------------------
  // Highest-trust regulatory and exchange sources
  // ---------------------------------------------------------------------------
  {
    sourceId: "sec-press-releases",
    name: "SEC Press Releases",
    description:
      "Official SEC press releases, enforcement actions, market-regulatory announcements, policy updates, and investor alerts.",
    sourceUrl: "https://www.sec.gov/news/pressreleases.rss",
    sourceTier: "official-regulatory",
    category: "Regulatory / Legal",
    enabled: true,
    minScoreToRetain: 52,
    minScoreToAlert: 84,
    maxItemsPerRun: 30,
    cooldownMinutes: 10,
    priority: 1,
  },
  {
    sourceId: "sec-structured-us-gaap",
    name: "SEC Structured Disclosure Feed",
    description:
      "SEC structured disclosure feed for XBRL submissions, accounting-related disclosures, and filing materials.",
    sourceUrl: "https://www.sec.gov/Archives/edgar/usgaap.rss.xml",
    sourceTier: "official-regulatory",
    category: "SEC Filings",
    enabled: true,
    minScoreToRetain: 50,
    minScoreToAlert: 82,
    maxItemsPerRun: 30,
    cooldownMinutes: 10,
    priority: 1,
  },
  {
    sourceId: "nasdaq-trade-halts",
    name: "Nasdaq Trade Halts",
    description:
      "Nasdaq Trader RSS feed for trading halts, resumptions, volatility pauses, and urgent exchange-level events.",
    sourceUrl: "https://www.nasdaqtrader.com/rss.aspx?feed=tradehalts",
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 40,
    minScoreToAlert: 78,
    maxItemsPerRun: 30,
    cooldownMinutes: 5,
    priority: 1,
  },
  {
    sourceId: "nasdaq-current-headlines",
    name: "Nasdaq Trader Current Headlines",
    description:
      "Nasdaq Trader current headline feed for exchange alerts, market-structure notices, and trading-related updates.",
    sourceUrl:
      "https://www.nasdaqtrader.com/rss.aspx?categorylist=0&feed=currentheadlines",
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 50,
    minScoreToAlert: 82,
    maxItemsPerRun: 30,
    cooldownMinutes: 10,
    priority: 2,
  },

  // ---------------------------------------------------------------------------
  // Macro, central bank, fiscal, labour, inflation, and economic data sources
  // ---------------------------------------------------------------------------
  {
    sourceId: "federal-reserve-all-press",
    name: "Federal Reserve Press Releases",
    description:
      "Federal Reserve official press releases covering policy, supervision, bank regulation, monetary policy, and system announcements.",
    sourceUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
    sourceTier: "macro-source",
    category: "Macro / Rates",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 84,
    maxItemsPerRun: 25,
    cooldownMinutes: 15,
    priority: 2,
  },
  {
    sourceId: "federal-reserve-monetary-policy",
    name: "Federal Reserve Monetary Policy",
    description:
      "Federal Reserve monetary policy updates, rate-sensitive policy statements, and central-bank communications.",
    sourceUrl: "https://www.federalreserve.gov/feeds/press_monetary.xml",
    sourceTier: "macro-source",
    category: "Macro / Rates",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 86,
    maxItemsPerRun: 20,
    cooldownMinutes: 15,
    priority: 2,
  },
  {
    sourceId: "federal-reserve-speeches",
    name: "Federal Reserve Speeches",
    description:
      "Federal Reserve speeches that may influence rate expectations, inflation outlook, policy positioning, and asset prices.",
    sourceUrl: "https://www.federalreserve.gov/feeds/speeches.xml",
    sourceTier: "macro-source",
    category: "Macro / Rates",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 88,
    maxItemsPerRun: 20,
    cooldownMinutes: 30,
    priority: 3,
  },
  {
    sourceId: "treasury-press-releases",
    name: "U.S. Treasury Press Releases",
    description:
      "U.S. Treasury releases related to fiscal policy, sanctions, debt issuance, financial stability, and market-sensitive government actions.",
    sourceUrl: "https://home.treasury.gov/rss/press-releases",
    sourceTier: "macro-source",
    category: "Macro / Fiscal Policy",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 88,
    maxItemsPerRun: 25,
    cooldownMinutes: 20,
    priority: 3,
  },
  {
    sourceId: "bls-all-news",
    name: "BLS News Releases",
    description:
      "Bureau of Labor Statistics releases for CPI, PPI, employment, wages, productivity, and labour-market reports.",
    sourceUrl: "https://www.bls.gov/feed/news_release/all.xml",
    sourceTier: "macro-source",
    category: "Macro / Labour and Inflation",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 88,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 3,
  },
  {
    sourceId: "bea-news",
    name: "BEA News",
    description:
      "Bureau of Economic Analysis releases including GDP, personal income, consumer spending, trade, and corporate-profit data.",
    sourceUrl: "https://www.bea.gov/rss.xml",
    sourceTier: "macro-source",
    category: "Macro / Economic Data",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 88,
    maxItemsPerRun: 20,
    cooldownMinutes: 30,
    priority: 3,
  },
  {
    sourceId: "eia-today-in-energy",
    name: "EIA Today in Energy",
    description:
      "Energy Information Administration updates for oil, gas, electricity, renewables, inventories, and energy-market trends.",
    sourceUrl: "https://www.eia.gov/rss/todayinenergy.xml",
    sourceTier: "macro-source",
    category: "Commodities / Energy",
    enabled: true,
    minScoreToRetain: 60,
    minScoreToAlert: 88,
    maxItemsPerRun: 20,
    cooldownMinutes: 30,
    priority: 4,
  },

  // ---------------------------------------------------------------------------
  // Market news feeds
  // ---------------------------------------------------------------------------
  {
    sourceId: "marketwatch-top-stories",
    name: "MarketWatch Top Stories",
    description:
      "MarketWatch top stories for broad market, company, investor sentiment, macro, and sector movement context.",
    sourceUrl: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 62,
    minScoreToAlert: 90,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 5,
  },
  {
    sourceId: "marketwatch-market-pulse",
    name: "MarketWatch Market Pulse",
    description:
      "MarketWatch market pulse feed for faster market-moving headlines and investor-facing updates.",
    sourceUrl: "https://feeds.content.dowjones.io/public/rss/mw_marketpulse",
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 62,
    minScoreToAlert: 90,
    maxItemsPerRun: 30,
    cooldownMinutes: 10,
    priority: 5,
  },
  {
    sourceId: "cnbc-top-news",
    name: "CNBC Top News",
    description:
      "CNBC top news feed for market, economy, company, sector, technology, and global business developments.",
    sourceUrl: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 64,
    minScoreToAlert: 91,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 5,
  },
  {
    sourceId: "cnbc-markets",
    name: "CNBC Markets",
    description:
      "CNBC markets feed for equity markets, investor sentiment, rates, and fast-moving market headlines.",
    sourceUrl: "https://www.cnbc.com/id/15839135/device/rss/rss.html",
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 64,
    minScoreToAlert: 91,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 5,
  },
  {
    sourceId: "investing-com-news",
    name: "Investing.com News",
    description:
      "Investing.com market news for macro, equity, commodity, currency, and global-market updates.",
    sourceUrl: "https://www.investing.com/rss/news.rss",
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 65,
    minScoreToAlert: 92,
    maxItemsPerRun: 30,
    cooldownMinutes: 20,
    priority: 6,
  },
  {
    sourceId: "investing-com-stock-market-news",
    name: "Investing.com Stock Market News",
    description:
      "Investing.com stock market feed for equity-specific updates, sector movement, and company-related market news.",
    sourceUrl: "https://www.investing.com/rss/news_25.rss",
    sourceTier: "market-news",
    category: "Equities",
    enabled: true,
    minScoreToRetain: 65,
    minScoreToAlert: 92,
    maxItemsPerRun: 30,
    cooldownMinutes: 20,
    priority: 6,
  },
  {
    sourceId: "investing-com-economic-indicators",
    name: "Investing.com Economic Indicators",
    description:
      "Investing.com economic indicator feed for macro data, inflation, rates, labour, GDP, and market-sensitive releases.",
    sourceUrl: "https://www.investing.com/rss/news_95.rss",
    sourceTier: "macro-source",
    category: "Macro / Economic Data",
    enabled: true,
    minScoreToRetain: 62,
    minScoreToAlert: 90,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 6,
  },

  // ---------------------------------------------------------------------------
  // Crypto and digital asset feeds
  // ---------------------------------------------------------------------------
  {
    sourceId: "coindesk-rss",
    name: "CoinDesk",
    description:
      "CoinDesk digital asset feed for Bitcoin, Ethereum, ETF flows, regulation, exchanges, stablecoins, and institutional crypto adoption.",
    sourceUrl: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    sourceTier: "crypto-source",
    category: "Crypto / Digital Assets",
    enabled: true,
    minScoreToRetain: 66,
    minScoreToAlert: 92,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 6,
  },
  {
    sourceId: "cointelegraph-rss",
    name: "Cointelegraph",
    description:
      "Cointelegraph crypto feed for digital asset regulation, crypto markets, ETF trends, protocols, tokens, and blockchain infrastructure.",
    sourceUrl: "https://cointelegraph.com/rss",
    sourceTier: "crypto-source",
    category: "Crypto / Digital Assets",
    enabled: true,
    minScoreToRetain: 70,
    minScoreToAlert: 94,
    maxItemsPerRun: 25,
    cooldownMinutes: 20,
    priority: 7,
  },
  {
    sourceId: "decrypt-rss",
    name: "Decrypt",
    description:
      "Decrypt crypto and Web3 feed for digital asset policy, token markets, AI/crypto overlap, and consumer crypto adoption.",
    sourceUrl: "https://decrypt.co/feed",
    sourceTier: "crypto-source",
    category: "Crypto / Digital Assets",
    enabled: true,
    minScoreToRetain: 70,
    minScoreToAlert: 94,
    maxItemsPerRun: 25,
    cooldownMinutes: 25,
    priority: 7,
  },

  // ---------------------------------------------------------------------------
  // Venture, startups, technology, and AI infrastructure
  // ---------------------------------------------------------------------------
  {
    sourceId: "techcrunch-startups",
    name: "TechCrunch Startups",
    description:
      "TechCrunch startup feed for venture-backed companies, funding rounds, AI tools, software infrastructure, and startup-market signals.",
    sourceUrl: "https://techcrunch.com/category/startups/feed/",
    sourceTier: "venture-source",
    category: "Private Markets / Venture",
    enabled: true,
    minScoreToRetain: 68,
    minScoreToAlert: 94,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 7,
  },
  {
    sourceId: "techcrunch-venture",
    name: "TechCrunch Venture",
    description:
      "TechCrunch venture feed for venture capital, private market trends, early-stage funding, and startup financing activity.",
    sourceUrl: "https://techcrunch.com/category/venture/feed/",
    sourceTier: "venture-source",
    category: "Private Markets / Venture",
    enabled: true,
    minScoreToRetain: 68,
    minScoreToAlert: 94,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 7,
  },
  {
    sourceId: "techcrunch-artificial-intelligence",
    name: "TechCrunch AI",
    description:
      "TechCrunch AI feed for artificial intelligence, model infrastructure, AI software, and emerging AI companies.",
    sourceUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    sourceTier: "venture-source",
    category: "AI / Technology",
    enabled: true,
    minScoreToRetain: 66,
    minScoreToAlert: 92,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 7,
  },
  {
    sourceId: "venturebeat-ai",
    name: "VentureBeat AI",
    description:
      "VentureBeat AI feed for enterprise AI, AI infrastructure, model deployment, automation, and AI business trends.",
    sourceUrl: "https://venturebeat.com/category/ai/feed/",
    sourceTier: "venture-source",
    category: "AI / Technology",
    enabled: true,
    minScoreToRetain: 68,
    minScoreToAlert: 94,
    maxItemsPerRun: 25,
    cooldownMinutes: 30,
    priority: 7,
  },

  // ---------------------------------------------------------------------------
  // Demo feeds retained for development, fallback, and algorithm testing
  // ---------------------------------------------------------------------------
  {
    sourceId: "demo-sec",
    name: "Demo SEC Filing Feed",
    description:
      "Demo source used when live RSS feeds are unavailable or while testing the algorithm.",
    sourceUrl: null,
    sourceTier: "official-regulatory",
    category: "SEC Filings",
    enabled: true,
    minScoreToRetain: 55,
    minScoreToAlert: 88,
    maxItemsPerRun: 25,
    cooldownMinutes: 10,
    priority: 90,
  },
  {
    sourceId: "demo-exchange",
    name: "Demo Exchange Halt Feed",
    description:
      "Demo exchange source used to test trading-halt style urgency logic.",
    sourceUrl: null,
    sourceTier: "official-exchange",
    category: "Exchange Alerts",
    enabled: true,
    minScoreToRetain: 50,
    minScoreToAlert: 82,
    maxItemsPerRun: 20,
    cooldownMinutes: 5,
    priority: 90,
  },
  {
    sourceId: "demo-market",
    name: "Demo Market News",
    description:
      "Demo general market headlines used to validate company and sector matching.",
    sourceUrl: null,
    sourceTier: "market-news",
    category: "Market News",
    enabled: true,
    minScoreToRetain: 60,
    minScoreToAlert: 90,
    maxItemsPerRun: 30,
    cooldownMinutes: 15,
    priority: 91,
  },
  {
    sourceId: "demo-macro",
    name: "Demo Macro Feed",
    description:
      "Demo macro source for rates, yields, inflation, and bond-sensitive headlines.",
    sourceUrl: null,
    sourceTier: "macro-source",
    category: "Macro / Rates",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 86,
    maxItemsPerRun: 25,
    cooldownMinutes: 15,
    priority: 91,
  },
  {
    sourceId: "demo-earnings",
    name: "Demo Earnings Feed",
    description:
      "Demo earnings source for financial results, guidance, and margin commentary.",
    sourceUrl: null,
    sourceTier: "market-news",
    category: "Earnings / Guidance",
    enabled: true,
    minScoreToRetain: 58,
    minScoreToAlert: 86,
    maxItemsPerRun: 25,
    cooldownMinutes: 15,
    priority: 91,
  },
  {
    sourceId: "demo-crypto",
    name: "Demo Crypto Feed",
    description:
      "Demo crypto source for digital asset risk and institutional-flow headlines.",
    sourceUrl: null,
    sourceTier: "crypto-source",
    category: "Crypto / Digital Assets",
    enabled: true,
    minScoreToRetain: 65,
    minScoreToAlert: 92,
    maxItemsPerRun: 20,
    cooldownMinutes: 20,
    priority: 91,
  },
  {
    sourceId: "demo-venture",
    name: "Demo Venture Feed",
    description:
      "Demo venture source for private market and startup-theme categorization.",
    sourceUrl: null,
    sourceTier: "venture-source",
    category: "Private Markets / Venture",
    enabled: true,
    minScoreToRetain: 68,
    minScoreToAlert: 95,
    maxItemsPerRun: 15,
    cooldownMinutes: 30,
    priority: 91,
  },
  {
    sourceId: "demo-noise",
    name: "Demo Noisy Feed",
    description:
      "Low-trust demo source used to make sure promotional garbage is suppressed.",
    sourceUrl: null,
    sourceTier: "unknown",
    category: "Noise Testing",
    enabled: true,
    minScoreToRetain: 80,
    minScoreToAlert: 99,
    maxItemsPerRun: 5,
    cooldownMinutes: 60,
    priority: 99,
  },
];

export const DEFAULT_RETENTION_POLICY = {
  minScoreToStore: 60,
  minScoreToAlert: 88,
  maxRetainedPerRun: 50,
  maxRetainedDecisions: 900,
  maxRetainedRuns: 80,
  maxAlertEvents: 600,
  urgentRetentionDays: 60,
  reviewRetentionDays: 35,
  digestRetentionDays: 18,
  watchRetentionDays: 7,
  readAlertRetentionDays: 35,
};